version: 2
updates:
  - package-ecosystem: gomod
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
    labels:
      - 'go'
      - 'dependencies'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
    groups:
      actions:
        patterns:
          - "actions/*"
    labels:
      - 'dependencies'
      - 'github-actions'

  - package-ecosystem: github-actions
    directory: '.github/actions/build-wpm'
    schedule:
      day: saturday
      interval: weekly
    groups:
      actions:
        patterns:
          - 'actions/*'
    labels:
      - 'dependencies'
      - 'github-actions'
