name: build wpm cli

description: build wpm cli for different platforms

inputs:
  go-version:
    description: 'go version to use'
    default: '^1.23'
  go-os:
    description: 'go os to use'
    default: 'linux'
  go-arch:
    description: 'go arch to use'
    default: 'amd64'
  go-arm:
    description: 'go arm version to use'
    default: '7'

runs:
  using: 'composite'
  steps:
    - name: setup go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 #v5.5.0
      with:
        go-version: ${{ inputs.go-version }}

    - name: build wpm
      shell: bash
      run: ./.github/actions/build-wpm/scripts/binary
      env:
        GOOS: ${{ inputs.go-os }}
        GOARM: ${{ inputs.go-arm }}
        GOARCH: ${{ inputs.go-arch }}
