version: 2
updates:
  - package-ecosystem: gomod
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
    labels:
      - 'go'
      - 'dependencies'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
    groups:
      actions:
        patterns:
          - "actions/*"
    labels:
      - 'github-actions'
      - 'dependencies'
