#!/usr/bin/env sh
#
# Build a static binary for the host OS/ARCH
#

set -eu

. ./.github/actions/build-wpm/scripts/.variables

echo "building $(basename "${TARGET}")"

export GO111MODULE=on

if [ "$(go env GOOS)" = "windows" ]; then
    if [ ! -x "$(command -v goversioninfo)" ]; then
        >&2 echo "goversioninfo not found, skipping manifesting binary"
    else
        ./.github/actions/build-wpm/scripts/mkversioninfo
        (set -x ; go generate -v "${SOURCE}")
    fi
fi

(set -x ; go build -o "${TARGET}" -ldflags "${GO_LDFLAGS}" "${SOURCE}")

cd "$(dirname "${TARGET}")"
find . -type f -print0 | sort -z | xargs -r0 shasum -a 256 -b | sed 's# \*\./# *#' > $RUNNER_TEMP/checksums.txt
shasum -a 256 -U -c $RUNNER_TEMP/checksums.txt
mv $RUNNER_TEMP/checksums.txt .
cat checksums.txt | while read sum file; do
    case "${file#\*}" in
        wpm-*)
            echo "$sum $file" > "${file#\*}.sha256"
            ;;
    esac
done
cd -
