name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: read
    steps:
        - name: Set up Go
          uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
          with:
            go-version: "1.23"

        - name: Checkout repository
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

        - name: Check dependencies
          run: |
            go mod tidy
            git diff --exit-code go.mod

        - name: Lint
          uses: golangci/golangci-lint-action@ec5d18412c0aeab7936cb16880d708ba2a64e1ae # v6.2.0
